#include "ultrasonic.h"
#include "icu.h"
#include "std_types.h"
#include <util/delay.h>
#include<avr/io.h>
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;


/*Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver.
• Inputs: None
• Return: None*/
void Ultrasonic_init(void){

 ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};
 ICU_init(&ICU_Configurations);
 ICU_setCallBack(Ultrasonic_edgeProcessing);
 GPIO_setupPinDirection(ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, PIN_OUTPUT);
// GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT, ULTRASONIC_ECHO_PIN, PIN_INPUT);

}

/*Description
➢ Send the Trigger pulse to the ultrasonic.
• Inputs: None
• Return: None*/
void Ultrasonic_Trigger(void){

 GPIO_writePin(ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_HIGH);
 _delay_us(10);  // Delay for 10 us ;
 GPIO_writePin(ULTRASONIC_TRIG_PORT, ULTRASONIC_TRIG_PIN, LOGIC_LOW);
}

/*Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
• Inputs: None
• Return: The measured distance in Centimeter.*/
uint16 Ultrasonic_readDistance(void){
 if (g_edgeCount==2){
  g_edgeCount=0;
 }

 else if(g_edgeCount==0){
  Ultrasonic_Trigger();
 }
 return ((g_timeHigh)*0.017);
}

/*Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
• Inputs: None
• Return: None*/
void Ultrasonic_edgeProcessing(void){

 g_edgeCount++;
  if(g_edgeCount == 1)
  {
   /*
    * Clear the timer counter register to start measurements from the
    * first detected rising edge
    */
   ICU_clearTimerValue();
   /* Detect falling edge */
   ICU_setEdgeDetectionType(FALLING);
  }
  else if(g_edgeCount == 2)
  {
   /* Store the High time value */
   g_timeHigh = ICU_getInputCaptureValue();
   ICU_setEdgeDetectionType(RAISING);
  }
}
